### ISSUE TITLE
Help testing against edge resque

### ISSUE THREAD

**Issue by steveklabnik** [kmullin/resque-sliders#2]
Hey there! 

I'm gearing up to work on Resque 2.0, and I'd like to coordinate better with plugin authors to make sure stuff doesn't break.

I'd like to know a few things:
1. Can I do something to help get you testing against edge Resque?
2. Are you monkey-patching anything in Resque currently? Can 2.0 expose an API to help you not have to do that any more?
3. Do you need any help in bringing your plugin up-to-date with the latest Resque?

Thanks!

Related: https://github.com/defunkt/resque/issues/880

**Comment by kmullin** [comment]
hey, thanks for reaching out.

according to [UPGRADING.md](https://github.com/resque/resque/blob/master/UPGRADING.md) I'll have to change the way I spawn resque workers.

could you tell me if you're going to change the single fork architecture?

**Comment by steveklabnik** [comment]
> could you tell me if you're going to change the single fork architecture?

It's on the docket for the future but I don't know if it'll be a 2.0 or 2.1 thing.

**Comment by kmullin** [comment]
And will there be any plans for having a single parent watch multiple workers?

Because that's what this plugin essentially is.

**Comment by steveklabnik** [comment]
Not 100% sure of that yet. If there's a plugin, I don't know why we'd bother pulling it up into core.
